var GAME_LEVELS = [
  ["             v                                                                  ",
   "                                                                                ",
   "                 v                                                              ",
   "                                                                                ",
   "                     v                                                          ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                           xx   vxx!xxv         ",
   "                                    o o                          x!!!x          ",
   "                x  x                                             xx!xx          ",
   "               x    x               xxvxx                         xvx           ",
   "              x!!!!!!x                                            xxx           ",
   "  xx          x!!!!!!x           o o                              xxx           ",
   "  x           x!!!!!!x     o       o              o o                    x      ",
   "  x           x!!!!!!x               xxxxx     xxxxx                    o x     ",
   "  x         xxxxxxxxxxx  x   o                                               o  ",
   "  x  @      xx       xx                                  xxx           xxxxxxxxx",
   "  xxxxxxxxxxxx       xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx          xxxxxxxx        ",
   "                              x   x                  x          x               ",
   "                              x!!!x                  x!!!!!!!!!!x               ",
   "                              x!!!x                  x!!!!!!!!!!x               ",
   "                              xxxxx                  xxxxxxxxxxxx               "],                                                                                
  ["                         x   xxxxx   xxxxx   xxxxx   xxxxx   xxxxx   xxxxx   xxxxx   xxxxx                    ",
   "                         x   x   x   x   x   x   x   x   x   x   x   x   x   x   x   x   x                    ", 
   "                         x   x   x   x   x   x   x   x   x   x   x   x   x   x   x   x   x                    ",
   "                         x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x                    ",
   "                         x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x                    ",
   "                         x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x                    ", 
   "                         x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x!!!x   x                    ",
   "                         xvxvx   xvxvx   xvxvx   xvxvx   xvxvx   xvxvx   xvxvx   xvxvx   x                    ",
   "                                                                                                              ",
   "                                                       v                                                      ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                   o                                          ",
   "               xxxxxxx  x    xxxx   x                              x   x      o  x     v   x                  ",
   "              xx     xx         x   x                             xx   x    xxxxxxxx       x                  ",
   "           x xx       xx        x o x                            x x   x   o               x                  ",
   "     @       x         x        x   x           x           o x   x   x   x               x                   ",
   "    xxx  x   x         x        x   x           x         xxxx     x   xxxxx   xxxxxx      x                  ",
   "    x x      x         x       xx o xx!!!!!!!!!!x                  x     o     x x         x                  ",
   "!!!!x x!!!!!!x         x!!!!!!!x     xx!!!!!!!!xx      x!!!!!!!!!x  x  x     =     x x         x              ",
   "!!!!x x!!!!!!x         x!!!!!!!x   o   xxxxxxxxxx     x!!!!!!!!!x!   xxxxxxxxxxxxxxx xx  o o  xx              ",
   "!!!!x x!!!!!!x         x!!!!!!!x      o              xx!!!!!!!xx !                    xx     xx               ",
   "!!!!x x!!!!!!x         x!!!!!!!x                    xxx!!!!!!xx  !                     xxxxxxx                ",
   "!!!!x x!!!!!!x         x!!!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                            ",
   "!!!!x x!!!!!!x         x!!!!!!!xxxxxxxxxx!!!!!!!!!!!!!!!!!xx    !                                             ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "             o                                                                                                ",
   "            xxx                                                                                               ",
   "           x!!!x                                                                                              ",
   "          x!!!!!x                                                                                             ",
   "           x!!!x    x   o                                                                                     ",
   "        x   x!x     v   x   xxx             x   xxxxxxxxxxxxxxxxxxxxxxx                                       ",
   "      x      v               xx           xx                                         xxx                      ",
   "  xxx                         x     o     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x   xxxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx xxx       x                              x x x                            x  ",
   "  x                 o                     x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x              xxxxxxx      x    xxx    x                             x x        xxx          xxx        x  ",
   "  x             xxxxxxxxx     xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @     xxxxxxxxxxx    x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "       v       v        v        v       v         v         v          v          v                          ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "            o                                                                                                 ",
   "           xxx      o           o               xxx   xx                                                      ",
   "        o          xxx         xxx                                                                            ",
   "       xxx          v           v         xxx                                                                 ",
   "             o            o                               o                     x      x                      ",
   "                                      o                  xxx     xx                                           ",
   "             xxx         xxx         xxx        xxx                     x                  x                  ",
   "                                                 v                                                            ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
